from .helpers import deformate_string
from .customer_deformation import CustomerDeformationInterface, CustomerDeformation
from .order_item_deformation import OrderItemDeformation,OrderItemDeformationInterface
from .manufacturer_deformation import ManufacturerDeformation, ManufacturerDeformationInterface
from .categoty_deformation import CategoryDeformation, CategoryDeformationInterface
from .comment_deformation import CommentDeformation, CommentDeformationInterface
from .product_deformation import ProductDeformation, ProductDeformationInterface
from .order_deformation import OrderDeformation, OrderDeformationInterface 
from .shipping_deformation import ShippingDeformation, ShippingDeformationInterface
from .discount_deformation import DiscountDeformation, DiscountDeformationInterface
from .supplier_deformation import SupplierDeformation, SupplierDeformationInterface
from .packaging_deformation import PackagingDeformation, PackagingDeformationInterface
from .payment_deformation import PaymentDeformation, PaymentDeformationInterface