version: '3'

services:

  maria-db:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword   # user=root 
    volumes:
      - db_data:/var/lib/mysql
      
volumes:
  db_data: